[package]
name = "json-curriculum-vitae"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "json-curriculum-vitae.typ"
authors = ["n4n5 <its.just.n4n5@gmail.com>"]
license = "MIT"
description = "Create a CV from a JSON file"
keywords = ["CV", "Curriculum Vitae", "json"]
categories = ["cv"]
disciplines = []
exclude = ["demo"]
repository = "https://github.com/Its-Just-Nans/typst-json-curriculum-vitae"
